version: '3'
services:
  mariadb:
    container_name: mariadb
    image: mariadb
    networks:
      - inception
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
      args:
        SQL_DATABASE : $SQL_DATABASE
        SQL_USER : $SQL_USER
        SQL_PASSWORD : $SQL_PASSWORD
        SQL_ROOT_PASSWORD : $SQL_ROOT_PASSWORD
    env_file: .env
    volumes:
      - type: volume
        source: mariadb
        target: /var/lib/mysql
    restart: unless-stopped
    expose:
      - "3306"

  nginx:
    container_name: nginx
    image: nginx
    depends_on:
    - wordpress
    volumes:
      - type: volume
        source: wordpress
        target: /var/www/wordpress
    networks:
    - inception
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "443:443"
    restart: on-failure

  wordpress:
    container_name: wordpress
    image: wordpress
    env_file: .env
    volumes:
      - type: volume
        source: wordpress
        target: /var/www/wordpress
    networks:
      - inception
    build: 
      context: requirements/wordpress
      dockerfile: Dockerfile
    depends_on:
      - mariadb
    restart: on-failure
    expose:
      - "9000"

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/syluiset/data/wordpress'

  mariadb:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/syluiset/data/mariadb'

networks:
  inception:
    driver: bridge
    name: inception
    